air_quality:
  target: dev
  outputs:
    dev:
      type: postgres
      host: ep-curly-glade-aomugt1b.c-2.ap-southeast-1.aws.neon.tech  
      port: 5432
      user: neondb_owner
      password: npg_EoGr4zm0udtM
      dbname: neondb
      schema: public
      threads: 4